export function makeFileName (name: string) {
  return name.charAt(0).toUpperCase() + name.slice(1)
}

export const eventList = {
  applicationCommandCreate: 'command: ApplicationCommand',
  applicationCommandDelete: 'command: ApplicationCommand',
  applicationCommandUpdate: 'before: ApplicationCommand | null, after: ApplicationCommand',
  channelCreate: 'channel: GuildChannel',
  channelDelete: 'channel: DMChannel | GuildChannel',
  channelPinsUpdate: 'channel: TextBasedChannels, date: Date',
  channelUpdate: 'before: DMChannel | GuildChannel, after: DMChannel | GuildChannel',
  debug: 'message: string',
  warn: 'message: string',
  emojiCreate: 'emoji: GuildEmoji',
  emojiDelete: 'emoji: GuildEmoji',
  emojiUpdate: 'before: GuildEmoji, after: GuildEmoji',
  error: 'error: Error',
  guildBanAdd: 'ban: GuildBan',
  guildBanRemove: 'ban: GuildBan',
  guildCreate: 'guild: Guild',
  guildDelete: 'guild: Guild',
  guildUnavailable: 'guild: Guild',
  guildIntegrationsUpdate: 'guild: Guild',
  guildMemberAdd: 'member: GuildMember',
  guildMemberAvailable: 'member: GuildMember | PartialGuildMember',
  guildMemberRemove: 'member: GuildMember | PartialGuildMember',
  guildMembersChunk: '',
  guildMemberUpdate: 'before: GuildMember | PartialGuildMember, after: GuildMember',
  guildUpdate: 'before: Guild, after: Guild',
  inviteCreate: 'invite: Invite',
  inviteDelete: 'invite: Invite',
  message: 'message: Message',
  messageCreate: 'message: Message',
  messageDelete: 'message: Message | PartialMessage',
  messageReactionRemoveAll: 'message: Message | PartialMessage',
  messageReactionRemoveEmoji: 'reaction: MessageReaction | PartialMessageReaction',
  messageDeleteBulk: 'messages: Collection<Snowflake, Message | PartialMessage>',
  messageReactionAdd: 'reaction: MessageReaction | PartialMessageReaction, user: User | PartialUser',
  messageReactionRemove: 'reaction: MessageReaction | PartialMessageReaction, user: User | PartialUser',
  messageUpdate: 'before: Message | PartialMessage, after: Message | PartialMessage',
  presenceUpdate: 'before: Presence | null, after: Presence',
  rateLimit: 'rateLimitData: RateLimitData',
  invalidRequestWarning: 'invalidRequestWarningData: InvalidRequestWarningData',
  ready: 'client: Client<true>',
  invalidated: '',
  roleCreate: 'role: Role',
  roleDelete: 'role: Role',
  roleUpdate: 'before: Role, after: Role',
  threadCreate: 'thread: ThreadChannel',
  threadDelete: 'thread: ThreadChannel',
  threadListSync: 'threads: Collection<Snowflake, ThreadChannel>',
  threadMemberUpdate: 'before: ThreadMember, after: ThreadMember',
  threadMembersUpdate: '',
  threadUpdate: 'before: ThreadChannel, after: ThreadChannel',
  typingStart: 'typing: Typing',
  userUpdate: 'before: User | PartialUser, after: User',
  voiceJoin: 'state: VoiceState',
  voiceLeave: 'state: VoiceState',
  voiceStateUpdate: 'before: VoiceState, after: VoiceState',
  webhookUpdate: 'channel: TextChannel',
  interactionCreate: 'interaction: Interaction',
  shardDisconnect: 'closeEvent: CloseEvent, shardId: number',
  shardError: 'error: Error, shardId: number',
  shardReady: 'shardId: number, unavailableGuilds: Set<Snowflake> | undefined',
  shardReconnecting: 'shardId: number',
  shardResume: 'shardId: number, replayedEvents: number',
  stageInstanceCreate: 'stageInstance: StageInstance',
  stageInstanceUpdate: 'before: StageInstance | null, after: StageInstance',
  stageInstanceDelete: 'stageInstance: StageInstance',
  stickerCreate: 'sticker: Sticker',
  stickerDelete: 'sticker: Sticker',
  stickerUpdate: 'before: Sticker, after: Sticker',
}